# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edaf44a5580f7218fcd0957cb331ce46622bb3e47fa819eb5d3846487081cd8b86535681fc6ebe2736ef05a728af2174e4a04edb4bd5a6ed923734811d9b140d

test:
  secret_key_base: e3200ee6c31e2f82e59afae9736e5e23d531b9f1d4dcad6c6281ba4adbaa12b0c3856634ef9ddfb2e33154a1d5e5ffd31523e837fb119f50440d84615e729da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
